import Head from "next/head"

const Page =()=>{
    return(<>
    <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>ABOUT US</div>
    </>)
}
export default Page